package accessModifiers._School_;

// On our top-level class we can use only two access modifiers(i.e (public and default))... (not private)...
//class _College_ { by making this class default ,meaning this class is not accessible from outside its own package...
public class _College_ {

    // we are taking the same reference of this class
    // CGC : is known as instance here...
    private static _College_ CGC; // Here we declare a variable of '_College_' datatype...

    // Private constructor...
    private _College_(){};

    // Here '_College_' is the data type which is used in this method
    // because we will return the instance of '_College_' Class..
    // this method will allow us to create this class object only once,because the instance(CGC) value will be null initially only...
    // After creating the object the instance(CGC) value changes...
    // so if we call this method again it won't create the new object again...
    public static _College_ getInstance(){

        if(CGC == null){
            CGC = new _College_(); // we can use private constructor within the same class...
            System.out.println("the instance is created...");
        }
        return CGC;
    }
}
