package MULTI_THREADING.ExecutersFrameworks.EXAMPLES;

import java.util.concurrent.*;

public class MAIN_2 {
    public static void main(String[] args) throws ExecutionException, InterruptedException {
        ExecutorService executor = Executors.newSingleThreadExecutor();
        // this 'future<?>' means we can return any-type of datatype variable...
        Future<?> future = executor.submit(() -> 42); // here we are returning 42...
        System.out.println(future.get()); // it will print the return value...
        if(future.isDone()){
            System.out.println("The task is done...");
        }
        executor.shutdown();

//  DIFFERENCE BETWEEN RUNNABLE AND CALLABLE INTERFACES:------------------------>
    // The main difference b/w them: is when we want to give executor a task in which it will return something ,then we should use 'Callable' interface 'call' method , else we should use 'Runnable' interface 'run' method...

        ExecutorService executor_2 = Executors.newSingleThreadExecutor();
        // Runnable Interface:-->
        // It will give us an error because 'Runnable' Interface 'run' method is of 'void' dataType...
        // Runnable runnable = ()->"Hello";  // it will give us error because, here we are returning String...
        // Future<?> future2 = executor_2.submit(runnable); it will also won't work...

        // Callable Interface:-->
        // Here: it will not give an error because 'Callable' Interface 'call' method can return any dataType...
        Callable<?> callable = ()->"hello"; // it will not give us error because, we can return anything here ...
        Future<?> future2 = executor_2.submit(callable); // it will also work here...
        System.out.println(future2.get());
        executor_2.shutdown();


    // Executor 3rd 'Submit()' type:---------------------------------->
        ExecutorService executor3 = Executors.newSingleThreadExecutor();
        // This 'submit()' takes an 'runnable task' and 'result' (that will be stored in a local variable only if the task is submitted successfully)...
        Future<String> future3 = executor3.submit(() -> System.out.println("Hi"), "sucess");
        System.out.println(future3.get()); // it will print result(i.e "success")...
        executor3.shutdown();
        System.out.println(executor3.isShutdown()); // it will return true if executor3 is shutDown...
        System.out.println(executor3.isTerminated()); // it will
    }
}
