package wrapperClasees;

public class wrapperClass {
    public static void main(String[] args) {
        int a = 1; // Here 'a' is the primitive variable, the data here is stored in stack...

        // Integer: it is a wrapper class...
        // By creating the object of the Wrapper class. we can use methods of the class...
        Integer b = 4; // Here 'b' is the reference variable (because 'Integer' is a class), the data here is stored in heap...
        String str =  b.toString(); // Here we are able to use the 'Integer' class methods with the help of b ...
        System.out.println(str);

        boolean hasGraphicCard = true; // Here 'hasGraphicCard' is the primitive variable, the data here is stored in stack...
        Boolean hasSuperPower = false; // Here 'hasSuperPower' is the reference variable (because 'Boolean' is a class), the data here is stored in heap...
        System.out.println(hasSuperPower.hashCode());  // Here we are able to use the 'Boolean' class methods with the help of  hasSuperPower ...

        // similarly...
        Float f = 1.65f;
        Double d = 12.64;

    }
}
